// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 4);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "ZA");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200110142707");
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"32e054a7-41ed-4353-9679-776efbfbd7b3\",\"default-theme@mozilla.org\":\"9763f0e8-7924-4fee-8a6e-1e7a0d01678e\",\"google@search.mozilla.org\":\"14cc9a3a-2dfb-4331-811f-6d5eca08c5b2\",\"amazondotcom@search.mozilla.org\":\"a52da5d7-c1ca-4cf8-81ef-9717fc4bd2fa\",\"bing@search.mozilla.org\":\"a656ebba-5932-431b-85e8-0aaa5bce0b51\",\"ddg@search.mozilla.org\":\"a790ee22-12fe-4c24-9045-40a697e88e58\",\"twitter@search.mozilla.org\":\"08fa603c-28d3-4d5d-aa2c-658d103f10a6\",\"wikipedia@search.mozilla.org\":\"e2d97352-2784-47d9-b449-1b8a0aa1bffa\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "da6d546e-ec9a-4c09-a97c-c9058c2f25f");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "f47bd7ae-cc81-4a5f-9387-7059d7438aa4");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
