// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200217142647");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.user_id", "10dbcc3c-1c6b-4604-8207-8133493160a8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1583144317);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1583144437);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1583143957);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1583415939);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1583144077);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1583144197);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1583143987);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1583144557);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 537);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1583143927);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{76183f1e-5aa3-443c-b5d9-3e134db7b9c4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1583415942401");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1583417714401");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1583143932161");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1583147532161");
user_pref("browser.search.region", "ZA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200217142647");
user_pref("browser.slowStartup.averageTime", 2408);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200217142647");
user_pref("browser.startup.homepage_override.mstone", "73.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1583415973);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1583143930895");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "73.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "5d64c57fa2b94e65bad82561e157ef09");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Sat, 29 Feb 2020 13:02:27 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1583144318);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200217142647");
user_pref("extensions.lastAppVersion", "73.0.1");
user_pref("extensions.lastPlatformVersion", "73.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c44c73b3-0256-45f1-8ee9-5c9b6d7403b1\",\"formautofill@mozilla.org\":\"80ba4b0a-51a7-40c0-bc49-f3679e89db1c\",\"screenshots@mozilla.org\":\"c7bbd43e-8be5-4d64-88bf-e5e4a0e02915\",\"webcompat-reporter@mozilla.org\":\"a1ad82b4-cb5b-414a-9a75-e3e9eb4e33e9\",\"webcompat@mozilla.org\":\"1b88150b-d6bd-49a4-8aee-619d1eecc439\",\"default-theme@mozilla.org\":\"1674288a-1cdf-4aee-ac9d-922b2e635c7e\",\"google@search.mozilla.org\":\"f1fb4e9f-f0a6-4b94-88cd-bda829c56488\",\"amazondotcom@search.mozilla.org\":\"1924ecc1-c87f-4bf1-8638-42c66ba21093\",\"bing@search.mozilla.org\":\"beb1daf6-deac-419b-9020-9d50980bee5d\",\"ddg@search.mozilla.org\":\"216cc3b3-0393-4887-863c-31546bd396d5\",\"ebay@search.mozilla.org\":\"8aa9770f-3b94-4692-8af8-5354cd50a9b2\",\"twitter@search.mozilla.org\":\"7b1977a4-54df-4b40-85f2-00ada6018645\",\"wikipedia@search.mozilla.org\":\"1fc23dc6-33ff-49fe-adb5-52619ab36763\"}");
user_pref("idle.lastDailyNotification", 1583144746);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1583144251);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200117190643");
user_pref("media.gmp-manager.lastCheck", 1583144251);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1583144746);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f17d1dad-f3a0-40b6-a3b8-b8f09f5578a9");
user_pref("security.sandbox.plugin.tempDirSuffix", "398da03e-1b67-4811-98d2-f2de64f714e6");
user_pref("services.blocklist.addons.checked", 1583415945);
user_pref("services.blocklist.gfx.checked", 1583415945);
user_pref("services.blocklist.plugins.checked", 1583415945);
user_pref("services.settings.clock_skew_seconds", -7);
user_pref("services.settings.last_etag", "\"1583344365865\"");
user_pref("services.settings.last_update_seconds", 1583415945);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1583415945);
user_pref("services.settings.main.cfr-fxa.last_check", 1583415945);
user_pref("services.settings.main.cfr.last_check", 1583415945);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1583415945);
user_pref("services.settings.main.hijack-blocklists.last_check", 1583415945);
user_pref("services.settings.main.language-dictionaries.last_check", 1583415945);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1583415945);
user_pref("services.settings.main.sites-classification.last_check", 1583415945);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1583415945);
user_pref("services.settings.main.whats-new-panel.last_check", 1583415945);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1583144746);
user_pref("toolkit.startup.last_success", 1583415972);
user_pref("toolkit.telemetry.cachedClientID", "4cea8954-4b72-4d7f-afc4-5ed89307c263");
user_pref("toolkit.telemetry.previousBuildID", "20200217142647");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
